In [0]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf

In [4]:
sess = tf.InteractiveSession()
  
# Create two random 0-D Tensors X and Y of any distribution

x = tf.random_uniform([])
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)

print(sess.run(out))

1.5201252


In [6]:
# Create two 0-D tensors x and y randomly selected from the range -1 to 1

x = tf.random_uniform([], minval=-1, maxval=1)
y = tf.random_uniform([], minval=-1, maxval=1)
out = tf.cond(tf.less(x, y), lambda: x + y, lambda: x -y)

print(sess.run(out))

0.3006878


In [7]:
# Create a tensor and another tensor of the same size but initialized with zeros
# Return a boolean tensor with element wise comparision

x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)
out = tf.equal(x, y)
print(sess.run(out))

[[ True False False]
 [ True False False]]


In [12]:
# Create a tensor and get all the indices of the elements that are greater than
# 30 and then gather all those values using the indices

x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
                 30.97266006,  26.67541885,  38.08450317,  20.74983215,
                 34.94445419,  34.45999146,  29.06485367,  36.01657104,
                 27.88236427,  20.56035233,  30.20379066,  29.51215172,
                 33.71149445,  28.59134293,  36.05556488,  28.66994858])
indices = tf.where(tf.greater(x, 30))
result = tf.gather(x, indices)

print(sess.run(result))

[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [14]:
# Create a diagonal matrix with the diagonals ranging from 1 to 6

out = tf.diag(tf.range(1, 7))

print(sess.run(out))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [18]:
# Create a random 10 x 10 tensor and then get the determinant of it

x = tf.random_normal([10, 10])
result = tf.matrix_determinant(x)

print(sess.run(result))

-27.515368


In [23]:
# Create a 1D Tensor and get all the unique elements in the tensor

x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
y, idx = tf.unique(x)

print(sess.run(y))

[ 5  2  3 10  6  4  1  0  9]


In [70]:
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.

x = tf.random_normal([300, 1])
y = tf.random_normal([300, 1])

residual = x - y
res_avg = tf.reduce_mean(residual)

def f1():
  return tf.reduce_mean(tf.square(residual))

def f2():
  return tf.reduce_sum(tf.abs(residual))

out = tf.cond(res_avg < 0, f1, f2)

print(sess.run(out))

1.8944753
